name: Build and publish package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: write
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Cargo release
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}

